### ISSUE TITLE
Help: using mochawesome in GitlabCI

### ISSUE THREAD

**Issue by jasoncheng** [adamgruber/mochawesome#268]
Problem when using mochawesome into GitlabCI, 

let say i have many stages/jobs, 
but all i want is concat all result in one  document, please tell me how to do this. 

.gitlab-ci.yml

```
build:
  stage: build
  script: 
   - mocha test/ui --reporter mochawesome  reportDir=./report

test_ui:
  stage: test
  script:
   - mocha test/ui --reporter mochawesome  reportDir=./report

test_be:
  stage: test
  script:
  - mocha test/backend  --reporter mochawesome reportDir=./report

deploy:
  stage: deploy
- mocha test/backend  --reporter mochawesome reportDir=./report

```
many thanks for [mochawesome], it's really awesome.
